-- VS Code-style command palette: <Space>P, then type plain English.
-- Curated entries only (no auto-registration) to avoid duplicate cryptic items.
-- Entries without an implementation are "anonymous": they only add a searchable
-- label for an existing binding — nothing is rebound.
return {
  "mrjones2014/legendary.nvim",
  lazy = false,
  priority = 10000,
  opts = {
    keymaps = {
      -- core vim, in VS Code vocabulary
      { "y", description = "Copy selection to clipboard", mode = { "v" } },
      { "p", description = "Paste from clipboard", mode = { "n", "v" } },
      { "U", description = "UPPERCASE selection", mode = { "v" } },
      { "u", description = "lowercase selection", mode = { "v" } },
      { "~", description = "Toggle case of selection", mode = { "v" } },
      { "gUiw", description = "UPPERCASE word under cursor" },
      { "0", description = "Go to beginning of line", mode = { "n", "v" } },
      { "^", description = "Go to first non-blank character of line", mode = { "n", "v" } },
      { "$", description = "Go to end of line", mode = { "n", "v" } },
      -- indent width follows 'shiftwidth', auto-inferred per file by guess-indent
      { ">>", description = "Indent current line" },
      { "<<", description = "Unindent current line" },
      { ">", description = "Indent selection", mode = { "v" } },
      { "<", description = "Unindent selection", mode = { "v" } },
      { "gv", description = "Reselect last selection (e.g. to indent again)" },
      { "<C-t>", description = "Indent current line (while typing)", mode = { "i" } },
      { "<C-d>", description = "Unindent current line (while typing)", mode = { "i" } },
      -- AstroNvim defaults
      { "<Leader>ff", description = "Open file (fuzzy search)" },
      { "<Leader>fw", description = "Search text in project" },
      { "<Leader>fo", description = "Open recent file" },
      { "<Leader>e", description = "Toggle file explorer" },
      { "<Leader>o", description = "Toggle focus: file tree ↔ editor" },
      { "<Leader>w", description = "Save file" },
      { "<Leader>c", description = "Close file (buffer)" },
      { "]b", description = "Next editor tab (buffer)" },
      { "[b", description = "Previous editor tab (buffer)" },
      { "<Leader>fb", description = "Switch between open files (fuzzy list of buffers)" },
      { "<Leader>bb", description = "Pick open file from tabline (tabs)" },
      { "<C-^>", description = "Toggle between last two files (like Ctrl+Tab)" },
      { "<Leader>/", description = "Toggle comment", mode = { "n", "v" } },
      { "<Leader>lf", description = "Format document" },
      { "<Leader>uf", description = "Toggle format-on-save (this file)" },
      { "<Leader>uF", description = "Toggle format-on-save (all files)" },
      { "<Leader>la", description = "Code actions" },
      { "<Leader>lS", description = "Symbols outline (document symbols sidebar)" },
      { "<Leader>lr", description = "Rename symbol" },
      { "gd", description = "Go to definition" },
      { "K", description = "Show hover docs" },
      -- windows & splits
      { "\\", description = "Split editor down (horizontal split)" },
      { "|", description = "Split editor right (vertical split)" },
      { "<C-w>H", description = "Move window to far left" },
      { "<C-w>L", description = "Move window to far right" },
      { "<C-w>J", description = "Move window to bottom" },
      { "<C-w>K", description = "Move window to top" },
      { "<C-h>", description = "Go to left split / tmux pane" },
      { "<C-j>", description = "Go to below split / tmux pane" },
      { "<C-k>", description = "Go to above split / tmux pane" },
      { "<C-l>", description = "Go to right split / tmux pane" },
      -- buffers, i.e. open files ("editors" in VS Code)
      { "<Leader>bc", description = "Close other files (keep current)" },
      { "<Leader>bC", description = "Close all files" },
      -- folds
      { "zM", description = "Fold all" },
      { "zR", description = "Unfold all" },
      { "za", description = "Toggle fold under cursor" },
      -- more VS Code habits
      { "d0", description = "Delete to start of line" },
      { "<Leader>uZ", description = "Toggle zen mode" },
      { "<Leader>us", description = "Toggle spell checking (dictionary-based)" },
      { "<Leader>ft", description = "Change color theme" },
      { "<Leader>gg", description = "Open lazygit (pull, push, stash, branch, merge)" },
      { "<Leader>td", description = "Open lazydocker (containers, logs, exec, restart)" },
      { "<Leader>gl", description = "Git blame current line" },
      { "<Leader>gL", description = "Git blame current line (full)" },
      { "<Leader>gt", description = "Git status: pick from changed files" },
      { "<Leader>gb", description = "Git branches: pick / switch" },
      { "<Leader>gc", description = "Git commit log (repository)" },
      { "<Leader>gC", description = "Git commit log (current file)" },
      { "<Leader>go", description = "Open file in browser on git host (GitHub)" },
      { "<Leader>gd", "<Cmd>Gitsigns diffthis<CR>", description = "Git diff current file (side-by-side split)" },
      { "<Leader>gD", function() require("gitsigns").diffthis "~1" end, description = "Git diff current file against previous commit" },
      { "<Leader>gs", description = "Stage / unstage git change (hunk)", mode = { "n", "v" } },
      { "<Leader>gr", description = "Undo git change (discard hunk)", mode = { "n", "v" } },
      { "<Leader>gS", description = "Stage all changes in file" },
      { "<Leader>gR", description = "Undo all git changes in file" },
      { "]g", description = "Jump to next git change in file" },
      { "[g", description = "Jump to previous git change in file" },
      { "]G", description = "Jump to last git change in file" },
      { "[G", description = "Jump to first git change in file" },
      -- problems panel (trouble.nvim)
      { "<Leader>xx", description = "Problems panel: current file diagnostics" },
      { "<Leader>xX", description = "Problems panel: workspace diagnostics" },
      { "<Leader>xt", description = "Problems panel: TODOs / FIXMEs" },
      -- sticky scroll
      { "<Leader>uT", description = "Toggle sticky scroll (pinned def/class context)" },
      -- test runner (neotest)
      { "<Leader>Tt", description = "Run test under cursor" },
      { "<Leader>Tf", description = "Run all tests in file" },
      { "<Leader>Tp", description = "Run all tests in project" },
      { "<Leader>Td", description = "Debug test under cursor" },
      { "<Leader>To", description = "Show test output" },
      { "<Leader>T<CR>", description = "Toggle test summary sidebar" },
      -- task runner (overseer)
      { "<Leader>Mr", description = "Run task (reads .vscode/tasks.json)" },
      { "<Leader>Mt", description = "Toggle task runner panel" },
      -- surround (nvim-surround)
      { 'ysiw"', description = "Wrap word in quotes (surround)" },
      { "cs", description = 'Change surrounding quotes/brackets (e.g. cs"\')' },
      { "ds", description = 'Delete surrounding quotes/brackets (e.g. ds")' },
      { "S", description = 'Surround selection (then type " ( [ etc.)', mode = { "v" } },
      -- debugging (AstroNvim nvim-dap defaults; VS Code F-keys work too)
      { "<Leader>db", description = "Toggle breakpoint (F9)" },
      { "<Leader>dC", description = "Set conditional breakpoint" },
      { "<Leader>dB", description = "Clear all breakpoints" },
      { "<Leader>dc", description = "Debug: start / continue — picks configuration (F5)" },
      { "<Leader>do", description = "Debug: step over (F10)" },
      { "<Leader>di", description = "Debug: step into (F11)" },
      { "<Leader>dO", description = "Debug: step out" },
      { "<Leader>ds", description = "Debug: run to cursor" },
      { "<Leader>dp", description = "Debug: pause" },
      { "<Leader>dr", description = "Debug: restart" },
      { "<Leader>dq", description = "Debug: close session" },
      { "<Leader>dQ", description = "Debug: terminate session" },
      { "<Leader>du", description = "Toggle debugger UI (variables, stack, watches)" },
      { "<Leader>dR", description = "Debug: toggle REPL console" },
      { "<Leader>dh", description = "Debug: inspect variable under cursor" },
      { "<Leader>dE", description = "Debug: evaluate expression" },
      -- custom (defined in copypath.lua / grug-far.lua)
      { "u", description = "Undo" },
      { "<C-r>", description = "Redo" },
      { "<Leader>q", description = "Quit window" },
      { "<Leader>Q", description = "Quit Neovim" },
      { "<Leader>yp", description = "Copy absolute path of file" },
      { "<Leader>yr", description = "Copy relative path of file" },
      { "<Leader>yn", description = "Copy filename" },
      { "<Leader>ss", description = "Search & replace in project (with preview)" },
      { "<Leader>sw", description = "Search & replace word under cursor" },
      { "<Leader>sf", description = "Search & replace in current file" },
      { "<Leader>se", description = "Search & replace in files of same type as current" },
      { "<Leader>s", description = "Search & replace selection", mode = { "v" } },
      -- grug-far panel actions: only shown in the palette while inside the
      -- panel (ft filter). "," is the localleader, matching grug-far defaults.
      { ",j", description = "Apply this match and go to next", filters = { ft = "grug-far" } },
      { ",k", description = "Apply this match and go to previous", filters = { ft = "grug-far" } },
      { ",l", description = "Apply this line only (keep in list)", filters = { ft = "grug-far" } },
      { "dd", description = "Exclude this match from apply-all", filters = { ft = "grug-far" } },
      { ",s", description = "Apply all remaining matches", filters = { ft = "grug-far" } },
      { ",r", description = "Replace all (ignores exclusions)", filters = { ft = "grug-far" } },
      { ",v", description = "Apply all matches in this file", filters = { ft = "grug-far" } },
      { ",q", description = "Send results to quickfix list", filters = { ft = "grug-far" } },
      { ",o", description = "Open match location", filters = { ft = "grug-far" } },
      { ",i", description = "Preview match location", filters = { ft = "grug-far" } },
      { ",b", description = "Abort running search/replace", filters = { ft = "grug-far" } },
      { ",c", description = "Close search & replace panel", filters = { ft = "grug-far" } },
      { "g?", description = "Show panel help", filters = { ft = "grug-far" } },
      -- neo-tree sidebar actions (only shown while the sidebar is focused)
      { "]b", description = "Sidebar: next tab (File → Bufs → Git)", filters = { ft = "neo-tree" } },
      { "[b", description = "Sidebar: previous tab (Git → Bufs → File)", filters = { ft = "neo-tree" } },
      { "l", description = "Open file / expand folder", filters = { ft = "neo-tree" } },
      { "h", description = "Collapse folder / go to parent", filters = { ft = "neo-tree" } },
      { "?", description = "Show sidebar help (all tree actions)", filters = { ft = "neo-tree" } },
      -- diffview file panel actions (only shown while the git panel is focused)
      { "s", description = "Stage / unstage file under cursor", filters = { ft = "DiffviewFiles" } },
      { "S", description = "Stage all files", filters = { ft = "DiffviewFiles" } },
      { "U", description = "Unstage all files", filters = { ft = "DiffviewFiles" } },
      { "X", description = "Discard changes to file (restore committed state)", filters = { ft = "DiffviewFiles" } },
      { "<CR>", description = "Open diff for selected file", filters = { ft = "DiffviewFiles" } },
      { "<Tab>", description = "Open diff for next file", filters = { ft = "DiffviewFiles" } },
      { "L", description = "Show commit log", filters = { ft = "DiffviewFiles" } },
      { "g?", description = "Show git panel help", filters = { ft = "DiffviewFiles" } },
    },
    commands = {
      { ":enew", description = "New file (empty buffer in current window)" },
      -- line duplication & movement (built-in :t / :m; adjust the offset
      -- for bigger jumps, e.g. :m+5 or :t-3)
      { ":t.", description = "Copy line down (duplicate below)" },
      { ":t-1", description = "Copy line up (duplicate above)" },
      { ":'<,'>t'>", description = "Copy selection down (duplicate below)" },
      { ":'<,'>t'<-1", description = "Copy selection up (duplicate above)" },
      { ":m+1", description = "Move line down (:m+2 for two lines, ...)" },
      { ":m-2", description = "Move line up (:m-3 for two lines, ...)" },
      { ":'<,'>m'>+1", description = "Move selection down ('>+2 for two lines, ...)" },
      { ":'<,'>m'<-2", description = "Move selection up ('<-3 for two lines, ...)" },
      { ":sort", description = "Sort lines ascending" },
      { ":sort u", description = "Sort lines & remove duplicates" },
      { ":setfiletype ", description = "Change language mode (set filetype)", unfinished = true },
      { ":GuessIndent", description = "Detect indentation from file" },
      { ":RenderMarkdown toggle", description = "Toggle markdown preview (in-editor)" },
      { ":Neotree position=current", description = "Open file tree full screen (in current window)" },
      -- git diffs (diffview.nvim; panel has "Changes" = unstaged vs staged,
      -- "Staged changes" = staged vs committed)
      { ":DiffviewOpen", description = "Git changes: tree with unstaged & staged diffs (like VS Code)" },
      { ":DiffviewOpen -- %", description = "Diff current file (unstaged & staged sections)" },
      { ":DiffviewFileHistory %", description = "Git history of current file (diff per commit)" },
      { ":DiffviewToggleFiles", description = "Toggle git changes panel (staged & unstaged as separate trees)" },
      { ":DiffviewFocusFiles", description = "Focus git changes panel" },
      { ":Neotree git_status", description = "Sidebar: open Git tab (changed files tree)" },
      { ":Neotree buffers", description = "Sidebar: open Bufs tab (open files tree)" },
      { ":Neotree filesystem", description = "Sidebar: open File tab (file explorer)" },
      { ":DiffviewClose", description = "Close git diff view" },
      { ":windo diffthis", description = "Compare visible splits (diff)" },
      { ":diffoff!", description = "Turn off diff view" },
      { ":Lazy sync", description = "Update plugins" },
      { ":Mason", description = "Manage language tools (LSP, formatters, linters)" },
      { ":GrugFar", description = "Find & replace across project" },
      { ":checkhealth", description = "Diagnose Neovim health" },
    },
    funcs = {
      -- real function, not fed keystrokes: works from inside the neo-tree
      -- window too, where <Space> (leader) is taken by toggle-folder
      {
        function()
          if vim.bo.filetype == "neo-tree" then
            vim.cmd.wincmd "p"
          else
            vim.cmd.Neotree "focus"
          end
        end,
        description = "Switch focus between file tree and editor",
      },
      {
        function() require("dropbar.api").pick() end,
        description = "Breadcrumbs: pick path/symbol to jump to (like clicking VS Code breadcrumbs)",
      },
    },
  },
  keys = {
    -- Both bound: Ctrl+Shift+P for VS Code muscle memory (needs extended-keys
    -- support end to end), plain Ctrl+P for keyboards without Shift chords
    -- (e.g. Termux) and terminals that collapse C-S-p into C-p anyway.
    { "<C-p>", "<Cmd>Legendary<CR>", desc = "Command palette", mode = { "n", "v" } },
    { "<C-S-p>", "<Cmd>Legendary<CR>", desc = "Command palette", mode = { "n", "v" } },
  },
}
